In [226]:
import pandas as pd
import numpy as np
# example of one hot encoding for a neural network
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from keras.models import Sequential
from keras.layers import Dense
# import tensor as tf


import pandas as pd
import numpy as np
# example of one hot encoding for a neural network
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from keras.models import Sequential
from keras.layers import Dense
# Scaling
from sklearn.preprocessing import RobustScaler

# Train Test Split
from sklearn.model_selection import train_test_split

# Models
import torch
import torch.nn as nn
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier

# Metrics
from sklearn.metrics import accuracy_score, classification_report, roc_curve

# Cross Validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

print('Packages imported...')

Packages imported...


In [227]:
# load the train dataset
def load_dataset(train, test, evaluation):
	# load the dataset as a pandas DataFrame
	print("load the dataset as a pandas DataFrame")
	train = pd.read_csv(train)
	test = pd.read_csv(test)
	evaluation = pd.read_csv(evaluation)

	train = train.replace(np.nan, 'no_data').astype(str)
	test = test.replace(np.nan, 'no_data').astype(str)
	evaluation = evaluation.replace(np.nan, 'no_data').astype(str)

	print(train.info())

    # select columns
	print("select columns")
	train_df = train[['consumed_part_name','pfmea_potential_effect_of_failure','pfmea_severity']]
	print(train_df)
	# train_df['consumed_part_name'] = train_df['consumed_part_name'].fillna('0')
	# train_df['pfmea_potential_effect_of_failure'] = train_df['pfmea_potential_effect_of_failure'].fillna('0')
	# train_df['pfmea_severity'] = train_df['pfmea_severity'].fillna("0")
	test_df = test[['consumed_part_name','pfmea_potential_effect_of_failure','pfmea_severity']]
	print(test_df)
	# test_df['consumed_part_name'] = test_df['consumed_part_name'].fillna('0')
	# test_df['pfmea_potential_effect_of_failure'] = test_df['pfmea_potential_effect_of_failure'].fillna('0')
	# test_df['pfmea_severity'] = test_df['pfmea_severity'].fillna("0")
	evaluation_df = evaluation[['consumed_part_name','pfmea_potential_effect_of_failure','pfmea_severity']]
	print(evaluation_df)
	# evaluation_df['consumed_part_name'] = evaluation_df['consumed_part_name'].fillna('0')
	# evaluation_df['pfmea_potential_effect_of_failure'] = evaluation_df['pfmea_potential_effect_of_failure'].fillna('0')
	# evaluation_df['pfmea_severity'] = evaluation_df['pfmea_severity'].fillna("0")


	# retrieve numpy array
	print("retrieve numpy array")
	#Considering y variable holds numpy array
	# dataset_train = tf.convert_to_tensor(train_df, dtype=tf.int64)
	# dataset_test = tf.convert_to_tensor(test_df, dtype=tf.int64)
	# evaluation_test = tf.convert_to_tensor(evaluation_df, dtype=tf.int64)
	dataset_train = train_df
	dataset_test = test_df
	evaluation_test = evaluation_df
	# dataset_train = train_df.values
	# dataset_test = test_df.values
	# evaluation_test = evaluation_df.values

	# Define Features and Label
	feature = ['consumed_part_name','pfmea_potential_effect_of_failure']
	label = ['pfmea_severity']

	# split into input (X) and output (y) variables
	print("split into input (X) and output (y) variables")
	X_train = dataset_train[feature].values
	y_train = dataset_train[label].values

	X_test = dataset_test[feature].values
	y_test = dataset_test[label].values

	X_evaluation = evaluation_test[feature].values
	y_evaluation = evaluation_test[label].values


	# # format all fields as string
	# print("format all fields as string")
	# X_train = X_train.astype(str)
	# X_test = X_test.astype(str)
	# X_evaluation = X_evaluation.astype(str)
	# y_train = y_train.astype(str)
	# y_test = y_test.astype(str)
	# y_evaluation = y_evaluation.astype(str)

	# reshape target to be a 2d array
	print("reshape target to be a 2d array")
	y_train = y_train.reshape((len(y_train), 1))
	y_test = y_test.reshape((len(y_test), 1))
	y_evaluation = y_evaluation.reshape((len(y_evaluation), 1))

	print("Done")


	return X_train, y_train, X_test, y_test, X_evaluation, y_evaluation

In [228]:
# prepare input train data
def prepare_inputs(X_train, X_test, X_evaluation):
	print("prepare input train data")
	ohe = OrdinalEncoder()
	ohe.fit(X_train)
	X_train_enc = ohe.fit_transform(X_train)
	X_test_enc = ohe.fit_transform(X_test)
	X_evaluation_enc = ohe.fit_transform(X_evaluation)
	print("Done")
	return X_train_enc, X_test_enc, X_evaluation_enc

In [229]:
# prepare target
def prepare_targets(y_train, y_test, y_evaluation):
	print("prepare target")
	le = LabelEncoder()
	le.fit(y_train)
	y_train_enc = le.transform(y_train)
	y_test_enc = le.transform(y_test)
	y_evaluation_enc = le.transform(y_evaluation)
	print("Done")
	return y_train_enc, y_test_enc, y_evaluation_enc

In [230]:
train = 'training.csv'
test = 'test.csv'
evaluation = 'evaluation.csv'

In [231]:
# load the dataset
X_train, y_train, X_test, y_test, X_evaluation, y_evaluation = load_dataset(train, test, evaluation)

# prepare input data
X_train_enc, X_test_enc,X_evaluation_enc = prepare_inputs(X_train, X_test, X_evaluation)

# prepare output data
y_train_enc, y_test_enc, y_evaluation_enc = prepare_targets(y_train, y_test, y_evaluation)



load the dataset as a pandas DataFrame
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222911 entries, 0 to 222910
Data columns (total 30 columns):
 #   Column                               Non-Null Count   Dtype 
---  ------                               --------------   ----- 
 0   plant                                222911 non-null  object
 1   line_mrn                             222911 non-null  object
 2   sub_process_station                  222911 non-null  object
 3   task_number                          222911 non-null  object
 4   consumed_part_number                 222911 non-null  object
 5   task_list_description                222911 non-null  object
 6   consumed_part_top_number             222911 non-null  object
 7   consumed_part_name                   222911 non-null  object
 8   consumed_part_state                  222911 non-null  object
 9   consumed_part_description            222911 non-null  object
 10  consumed_part_assembly_instructions  222911 non-null 

/Users/ananya_pramanik/opt/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ananya_pramanik/opt/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [232]:
print('X_train',X_train.shape)
print('y_train',y_train.shape)
print('X_test',X_test.shape)
print('y_test',y_test.shape)
print('X_evaluation',X_evaluation.shape)
print('y_evaluation',y_evaluation.shape)

print('X_train_enc',X_train_enc.shape)
print('X_test_enc',X_test_enc.shape)
print('X_evaluation_enc',X_evaluation_enc.shape)

print('y_train_enc',y_train_enc.shape)
print('y_test_enc',y_test_enc.shape)
print('y_evaluation_enc',y_evaluation_enc.shape)

X_train (222911, 2)
y_train (222911, 1)
X_test (31845, 2)
y_test (31845, 1)
X_evaluation (63689, 2)
y_evaluation (63689, 1)
X_train_enc (222911, 2)
X_test_enc (31845, 2)
X_evaluation_enc (63689, 2)
y_train_enc (222911,)
y_test_enc (31845,)
y_evaluation_enc (63689,)


In [233]:
# define the  model
model = Sequential()
model.add(Dense(2, input_dim=X_train_enc.shape[1], activation='relu', kernel_initializer='he_normal'))
model.add(Dense(1, activation='softmax'))
# summarize layers
print(model.summary())

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_42 (Dense)            (None, 2)                 6         
                                                                 
 dense_43 (Dense)            (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [234]:
X_train_enc

array([[726.,   7.],
       [726.,   7.],
       [191.,   2.],
       ...,
       [890.,  21.],
       [890.,  18.],
       [626.,  21.]])

In [235]:
y_train_enc

array([6, 6, 7, ..., 5, 5, 5])

In [236]:
# compile the keras model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
#### train the model with epochs ####
epochs = 10
batch_size = 64
model.fit(X_train_enc, y_train_enc, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/10
3135/3135 [==============================] - 10s 3ms/step - loss: 0.0000e+00 - accuracy: 0.0013 - val_loss: 0.0000e+00 - val_accuracy: 1.7944e-04
Epoch 2/10
3135/3135 [==============================] - 7s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0013 - val_loss: 0.0000e+00 - val_accuracy: 1.7944e-04
Epoch 3/10
3135/3135 [==============================] - 5s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0013 - val_loss: 0.0000e+00 - val_accuracy: 1.7944e-04
Epoch 4/10
3135/3135 [==============================] - 4s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0013 - val_loss: 0.0000e+00 - val_accuracy: 1.7944e-04
Epoch 5/10
3135/3135 [==============================] - 4s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0013 - val_loss: 0.0000e+00 - val_accuracy: 1.7944e-04
Epoch 6/10
3135/3135 [==============================] - 3s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0013 - val_loss: 0.0000e+00 - val_accuracy: 1.7944e-04
Epoch 7/10
3135/3135 [==============================] - 4s 1ms/

In [238]:
# evaluate the keras model
test, accuracy = model.evaluate(X_evaluation_enc, y_evaluation_enc, verbose=0)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 0.12


In [239]:
testy_pred = model.predict(X_evaluation_enc)

1991/1991 [==============================] - 3s 1ms/step


In [240]:
testy_pred

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)